'use strict';

// BacklogTrace: EVC-003
module.exports = {
  DEFAULT_CHARGE_HOURS: 3,
  DEFAULT_CHARGER_KW: 11,
  DEFAULT_PRICE_AREA: 'DK2',
  DATASET: 'DayAheadPrices',
  NIGHT_CHARGE_WINDOW_START: 21,
  NIGHT_CHARGE_WINDOW_END: 6,
  DAY_CHARGE_WINDOW_START: 9,
  DAY_CHARGE_WINDOW_END: 17,
  DAY_PLAN_SWITCH_HOUR: 7,
  NIGHT_PLAN_SWITCH_HOUR: 17,
  DEFAULT_SPOT_CHARGE_THRESHOLD_KR_INCL_VAT: 0.30,
  SLOT_MINUTES: 15,
  VAT_MULTIPLIER: 1.25,
  STROMLIGNING_API_BASE_URL: 'https://stromligning.dk/api',
  STROMLIGNING_SUPPLIER_ID: 'elektrus_c',
  STROMLIGNING_CUSTOMER_GROUP_ID: 'c',
  STROMLIGNING_AGGREGATION: '1h',
  DEFAULT_ONE_SHOT_CHARGE_HOURS: 7,
  DEFAULT_ONE_SHOT_READY_BY: '09:30',
  DK_TIME_ZONE: 'Europe/Copenhagen',
  EVALUATION_INTERVAL_MS: 15 * 60 * 1000,
  LOGIC_VARIABLES: {
    FORCE_CHARGE: 'forceCharge',
    CHARGE_HOURS: 'ChargeHours',
    CHARGE_NOW: 'charge_now',
    CHARGE_MESSAGE: 'charge_message',
    ONE_SHOT_CHARGE: 'oneShotCharge',
    ONE_SHOT_CHARGE_HOURS: 'oneShotChargeHours',
    ONE_SHOT_READY_BY: 'oneShotReadyBy',
    STROMLIGNING_API_KEY: 'StromligningApiKey'
  }
};
