alias: "Deye-01 v1.0.10: SOC-Based Discharge Limiter (Authority Mode)"
description: "ðŸ”’ AUTHORITATIVE: Flat 60A above 45% SOC, exponential curve 15-45% SOC. EV charging = 0A for 1 hour. Uses real battery voltage. Enforces every 15s."
mode: queued
max: 10

triggers:
  # EV charging webhook from Homey
  - id: ev_webhook
    trigger: webhook
    webhook_id: deye_ev_start_easee

  # React immediately if someone changes the discharge cap (SolarBalance, etc.)
  - trigger: state
    entity_id: number.solarcust0186_maximum_battery_discharge_current

  # React to SOC changes
  - trigger: state
    entity_id: sensor.solarcust0186_battery_charge_level

  # HA startup
  - trigger: homeassistant
    event: start

  # Periodic authority check
  - trigger: time_pattern
    seconds: "/15"

conditions: []

actions:
  # Handle EV webhook first
  - if:
      - condition: template
        value_template: "{{ trigger.id == 'ev_webhook' }}"
    then:
      # Set EV charging active flag
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.deye_ev_charging_active
      
      # Set end time to 1 hour from now
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.deye_ev_charge_end_time
        data:
          datetime: "{{ (now() + timedelta(hours=1)).isoformat() }}"
      
      # Increment webhook counter for tracking
      - action: counter.increment
        target:
          entity_id: counter.deye_ev_webhook_count
      
      # Immediate notification
      - action: persistent_notification.create
        data:
          notification_id: deye_ev_webhook_received
          title: "âš¡ EV Charging Started"
          message: >
            Webhook received at {{ now().strftime('%H:%M:%S') }}
            Discharge will be 0A for 1 hour
            End time: {{ (now() + timedelta(hours=1)).strftime('%H:%M:%S') }}
  
  - variables:
      # Current sensor values
      soc: "{{ states('sensor.solarcust0186_battery_charge_level') | float(50) }}"
      batt_v: "{{ states('sensor.solarcust0186_battery_voltage') | float(48) }}"
      current_cap_a: "{{ states('number.solarcust0186_maximum_battery_discharge_current') | float(0) }}"

      # EV charging state - check if 1 hour has passed
      ev_end_time: "{{ states('input_datetime.deye_ev_charge_end_time') }}"
      ev_active_flag: "{{ is_state('input_boolean.deye_ev_charging_active', 'on') }}"
      ev_time_expired: "{{ ev_end_time != 'unknown' and now() >= (ev_end_time | as_datetime) }}"
      ev_charging: "{{ ev_active_flag and not ev_time_expired }}"

      # Curve params
      SOC_MAX: 45           # Above this: flat max power
      SOC_MIN: 15           # Below this: min power (floor)
      POWER_MAX: 2600       # Max curve power at 45% SOC (before boost)
      POWER_MIN: 800        # Min power at 15% SOC
      BOOST: 1.05           # 5% boost factor
      FLAT_DISCHARGE_A: 60  # Flat discharge above SOC_MAX

      # Connection state
      is_connected: "{{ is_state('binary_sensor.solarcust0186_connection_status', 'on') }}"

      # Check if EV charge timeout expired and cleanup needed
      cleanup_ev: "{{ ev_active_flag and ev_time_expired }}"

      # Determine target discharge: 0A if EV charging, otherwise SOC curve
      # IMPORTANT: if EV/other logic sets cap to 0, do not fight it
      cap_enabled: "{{ current_cap_a > 0 or ev_charging }}"

      # Compute watts limit (flat 60A above SOC_MAX, exponential curve below)
      soc_power_limit_w: >-
        {% if soc >= SOC_MAX %}
          {{ (FLAT_DISCHARGE_A * batt_v) | round(0) }}
        {% elif soc <= SOC_MIN %}
          {{ (POWER_MIN * BOOST) | round(0) }}
        {% else %}
          {% set normalized = (soc - SOC_MIN) / (SOC_MAX - SOC_MIN) %}
          {% set normalized = [0, [normalized, 1] | min] | max %}
          {% set exponential = normalized * normalized %}
          {{ ((POWER_MIN + (POWER_MAX - POWER_MIN) * exponential) * BOOST) | round(0) }}
        {% endif %}

      # Convert to amps using REAL voltage (avoid division by 0)
      soc_limit_a: >-
        {% set v = batt_v if batt_v > 1 else 48 %}
        {% if soc >= SOC_MAX %}
          {{ FLAT_DISCHARGE_A }}
        {% else %}
          {{ (soc_power_limit_w / v) | round(0) }}
        {% endif %}

      # Final target: 0A if EV charging, otherwise SOC curve limit
      target_discharge_a: "{{ 0 if ev_charging else soc_limit_a }}"

      # Only enforce if different
      needs_enforce: "{{ (current_cap_a | round(0) | int) != (target_discharge_a | round(0) | int) }}"

      # Only notify when SOC is below SOC_MAX or EV active
      notify_allowed: "{{ soc <= SOC_MAX or ev_charging }}"

  # Cleanup EV flag if timeout expired
  - if:
      - condition: template
        value_template: "{{ cleanup_ev }}"
    then:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.deye_ev_charging_active
      
      - action: persistent_notification.create
        data:
          notification_id: deye_ev_timeout
          title: "âœ… EV Charge Timeout"
          message: >
            1 hour expired at {{ now().strftime('%H:%M:%S') }}
            Discharge will resume per SOC curve

  # ENFORCE (authoritative)
  - if:
      - condition: template
        value_template: "{{ is_connected and cap_enabled and needs_enforce }}"
    then:
      - action: number.set_value
        target:
          entity_id: number.solarcust0186_maximum_battery_discharge_current
        data:
          value: "{{ target_discharge_a }}"

      - delay: "00:00:01"

      # Notify ONLY when SOC < 45% or EV active
      - if:
          - condition: template
            value_template: "{{ notify_allowed }}"
        then:
          - action: persistent_notification.create
            data:
              notification_id: deye_soc_limiter_enforced
              title: "âœ… Deye-01 ENFORCED v1.0.10"
              message: >
                â° {{ now().strftime('%H:%M:%S') }}
                {% if ev_charging %}
                âš¡ EV CHARGING MODE
                Discharge: 0A (until {{ as_timestamp(ev_end_time) | timestamp_custom('%H:%M:%S') }})
                {% else %}
                SOC: {{ soc | round(1) }}%
                Volt: {{ batt_v | round(2) }}V
                Cap: {{ current_cap_a | round(0) }}A â†’ {{ target_discharge_a | round(0) }}A
                {% if soc >= SOC_MAX %}
                Mode: FLAT MAX (60A)
                {% else %}
                Limit: {{ soc_power_limit_w | round(0) }}W (exponential curve)
                {% endif %}
                {% endif %}