alias: >-
  Deye-01 v1.0.38: SOC-Based Discharge Limiter (15-30% Curve, Voltage-Safe)
description: >
  üîí AUTHORITATIVE: Voltage protection ALWAYS active (49.8-51.2V zones).
  SOC curve: Flat 60A above 30%, exponential 15-30%, min 600W below 15%.
  Final limit = min(voltage_limit, soc_limit) √ó derating. Enforces every 15s.
triggers:
  - id: ev_webhook
    trigger: webhook
    webhook_id: deye_ev_start_easee
  - id: discharge_changed
    trigger: state
    entity_id: number.solarcust0186_maximum_battery_discharge_current
  - id: soc_changed
    trigger: state
    entity_id: sensor.solarcust0186_battery_charge_level
  - id: ha_start
    trigger: homeassistant
    event: start
  - id: periodic
    trigger: time_pattern
    seconds: /15
conditions: []
actions:
  - if:
      - condition: template
        value_template: "{{ trigger.id == 'ev_webhook' }}"
    then:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.deye_ev_charging_active
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.deye_ev_charge_end_time
        data:
          datetime: "{{ (now() + timedelta(hours=1)).isoformat() }}"
      - action: counter.increment
        target:
          entity_id: counter.deye_ev_webhook_count
      - action: persistent_notification.create
        data:
          notification_id: deye_ev_webhook_received
          title: ‚ö° EV Charging Started
          message: >
            Webhook received at {{ now().strftime('%H:%M:%S') }} Discharge will
            be 0A for 1 hour End time: {{ (now() +
            timedelta(hours=1)).strftime('%H:%M:%S') }}
  - variables:
      soc: "{{ states('sensor.solarcust0186_battery_charge_level') | float(50) }}"
      batt_v: "{{ states('sensor.solarcust0186_battery_voltage') | float(48) }}"
      current_cap_a: >-
        {{ states('number.solarcust0186_maximum_battery_discharge_current') |
        float(0) }}
      ev_end_time: "{{ states('input_datetime.deye_ev_charge_end_time') }}"
      ev_active_flag: "{{ is_state('input_boolean.deye_ev_charging_active', 'on') }}"
      ev_time_expired: |
        {% if ev_end_time == 'unknown' or ev_end_time == '' %}
          true
        {% else %}
          {{ now() >= (strptime(ev_end_time, '%Y-%m-%d %H:%M:%S') | as_local) }}
        {% endif %}
      ev_charging: "{{ ev_active_flag and not ev_time_expired }}"
      SOC_MAX: 30
      SOC_MIN: 15
      POWER_MAX: 3500
      POWER_MIN: 600
      BOOST: 1.05
      FLAT_DISCHARGE_A: 60
      prev_volt: "{{ states('input_number.deye_previous_voltage') | float(batt_v) }}"
      volt_delta: "{{ batt_v - prev_volt }}"
      volt_rate_per_min: "{{ (volt_delta / 15) * 60 }}"
      is_low_soc_zone: "{{ soc < 30 }}"
      fast_voltage_drop: "{{ volt_rate_per_min < -0.25 }}"
      cleanup_ev: "{{ ev_active_flag and ev_time_expired }}"
      voltage_hard_limit_w: |-
        {% if batt_v < 49.8 %}
          50
        {% elif batt_v < 50.2 %}
          300
        {% elif batt_v < 50.5 %}
          600
        {% elif batt_v < 50.8 %}
          900
        {% elif batt_v < 51.2 %}
          1200
        {% else %}
          9999
        {% endif %}
      soc_power_limit_w: |-
        {% if soc >= SOC_MAX %}
          {{ (FLAT_DISCHARGE_A * batt_v) | round(0) }}
        {% elif soc <= SOC_MIN %}
          {{ (POWER_MIN * BOOST) | round(0) }}
        {% else %}
          {% set normalized = (soc - SOC_MIN) / (SOC_MAX - SOC_MIN) %}
          {% set normalized = [0, [normalized, 1] | min] | max %}
          {% set exponential = normalized * normalized %}
          {{ ((POWER_MIN + (POWER_MAX - POWER_MIN) * exponential) * BOOST) | round(0) }}
        {% endif %}
      voltage_protected_w: "{{ [voltage_hard_limit_w, soc_power_limit_w] | min }}"
      soc_derating: |-
        {% if is_low_soc_zone and batt_v < 51.0 %}
          0.7
        {% elif fast_voltage_drop and batt_v < 51.5 %}
          0.6
        {% else %}
          1.0
        {% endif %}
      final_power_limit_w: "{{ (voltage_protected_w * soc_derating) | round(0) }}"
      soc_limit_a: |-
        {% set v = [batt_v, 48] | max %}
        {{ [(final_power_limit_w / v) | round(0), FLAT_DISCHARGE_A] | min }}
      target_discharge_a: "{{ 0 if ev_charging else soc_limit_a }}"
      cap_enabled: "{{ target_discharge_a > 0 or current_cap_a > 0 or ev_charging }}"
      needs_enforce: >-
        {{ (current_cap_a | round(0) | int) != (target_discharge_a | round(0) |
        int) }}
      safety_violation: "{{ current_cap_a > FLAT_DISCHARGE_A and soc >= SOC_MAX }}"
      notify_allowed: "{{ soc <= SOC_MAX or ev_charging }}"
  - if:
      - condition: template
        value_template: "{{ cleanup_ev }}"
    then:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.deye_ev_charging_active
      - action: persistent_notification.create
        data:
          notification_id: deye_ev_timeout
          title: ‚úÖ EV Charge Timeout
          message: >
            1 hour expired at {{ now().strftime('%H:%M:%S') }} Discharge will
            resume per SOC curve
  - if:
      - condition: template
        value_template: "{{ cap_enabled and needs_enforce }}"
    then:
      - action: number.set_value
        target:
          entity_id: number.solarcust0186_maximum_battery_discharge_current
        data:
          value: "{{ target_discharge_a }}"
      - action: input_number.set_value
        target:
          entity_id: input_number.deye_previous_voltage
        data:
          value: "{{ batt_v }}"
      - delay: "00:00:01"
      - if:
          - condition: template
            value_template: "{{ notify_allowed }}"
        then:
          - action: persistent_notification.create
            data:
              notification_id: deye_soc_limiter_enforced
              title: ‚úÖ Deye-01 ENFORCED v1.0.38
              message: >
                ‚è∞ {{ now().strftime('%H:%M:%S') }} {% if ev_charging %} ‚ö° EV
                CHARGING MODE Discharge: 0A (until {{ (ev_end_time |
                as_timestamp(0)) | timestamp_custom('%H:%M:%S', 'N/A') }}) {%
                else %} SOC: {{ soc | round(1) }}% Volt: {{ batt_v | round(2)
                }}V (Œî {{ volt_delta | round(2) }}V, {{ volt_rate_per_min |
                round(2) }}V/min) {% if fast_voltage_drop %} üö® FAST DROP (-{{
                (volt_rate_per_min * -1) | round(2) }}V/min) {% endif %} Power:
                {{ final_power_limit_w | round(0) }}W (volt={{ voltage_hard_limit_w }}W, soc={{ soc_power_limit_w }}W ‚Üí {{ voltage_protected_w }}W √ó
                {{ soc_derating }}x) Zone: {{ 'NORMAL' if batt_v >= 51.2 else
                ('SOFT1' if batt_v >= 50.6 else ('SOFT2' if batt_v >= 50.2 else
                ('CRITICAL' if batt_v >= 49.8 else 'CUTOFF'))) }} Cap: {{
                current_cap_a | round(0) }}A ‚Üí {{ target_discharge_a | round(0)
                }}A {% if soc >= SOC_MAX %} Mode: FLAT MAX (60A) {% else %} {%
                if is_low_soc_zone %} ‚ö†Ô∏è Low SOC derating (0.7x) {% endif %} {%
                endif %} {% endif %}
mode: queued
max: 10
