alias: "Deye-01: Rescue (Volt) FAST+Preemptive+DischargeCut"
description: "[v1.1.0] Battery rescue automation with multi-level volt protection (panic, hard, preemptive, soft). Enables grid charge with safeguards when voltage drops. Now signals Deye-08 to prevent interference."
tags:
  - deye-battery
  - rescue
  - critical
  - load-sensitive
triggers:
  - id: panic
    entity_id: sensor.solarcust0186_battery_voltage
    below: 47.8
    trigger: numeric_state

  - id: hard
    entity_id: sensor.solarcust0186_battery_voltage
    below: 48
    for: "00:00:05"
    trigger: numeric_state

  - id: preemptive_load
    value_template: |
      {{ (states('sensor.solarcust0186_battery_voltage') | float(999)) < 49.2
         and (states('sensor.solarcust0186_load_totalpower') | float(0)) > 2400 }}
    for: "00:00:20"
    trigger: template

  - id: preemptive_batt_high
    value_template: |
      {{ (states('sensor.solarcust0186_battery_voltage') | float(999)) < 49.4
         and (states('sensor.solarcust0186_battery_output_power') | float(0)) > 1500 }}
    for: "00:00:15"
    trigger: template

  - id: preemptive_batt_veryhigh
    value_template: |
      {{ (states('sensor.solarcust0186_battery_voltage') | float(999)) < 49.6
         and (states('sensor.solarcust0186_battery_output_power') | float(0)) > 2500 }}
    for: "00:00:10"
    trigger: template

  - id: soft
    value_template: |
      {{ (states('sensor.solarcust0186_battery_voltage') | float(999)) <
         (states('input_number.deye_trig_volt_soft_learned') | float(48.3)) }}
    for: "00:02:00"
    trigger: template

  - id: soc_load
    value_template: |
      {{ (states('sensor.solarcust0186_battery_charge_level') | float(100)) < 20
         and (states('sensor.solarcust0186_load_totalpower') | float(0)) > 2000 }}
    for: "00:02:00"
    trigger: template

conditions:
  - condition: state
    entity_id: binary_sensor.solarcust0186_connection_status
    state: "on"

  - condition: state
    entity_id: switch.solarcust0186_inverter_automations_on_off
    state: "on"

  - condition: template
    value_template: |
      {{ (states('sensor.solarcust0186_load_totalpower') | float(0)) > 1000 }}

actions:
  - variables:
      IS_FAST: >-
        {{ trigger.id in
        ['panic','hard','preemptive_load','preemptive_batt_high','preemptive_batt_veryhigh'] }}
      CHARGE_A: >-
        {{ CHARGE_A_FAST if (trigger.id in ['panic','hard']) else CHARGE_A_PRE }}
      LOOP_DELAY: "{{ '00:00:20' if IS_FAST else '00:01:00' }}"
      SOFT_VOLT: "{{ states('input_number.deye_trig_volt_soft_learned') | float(48.3) }}"
      DEYE08_ACTIVE: "{{ is_state('input_boolean.deye08_active','on') }}"

  - action: persistent_notification.create
    data:
      notification_id: "{{ NOTIFY_ID }}"
      title: Rescue charge
      message: >
        🟢 STARTET ({{ trigger.id|upper }}) Volt: {{
        states('sensor.solarcust0186_battery_voltage') }} V SOC: {{
        states('sensor.solarcust0186_battery_charge_level') }} % Load: {{
        states('sensor.solarcust0186_load_totalpower') }} W BattP: {{
        states('sensor.solarcust0186_battery_output_power') }} W SoftV: {{
        SOFT_VOLT }} V ChargeA: {{ CHARGE_A }} A DischargeSafe: {{
        DISCHARGE_A_SAFE }} A Deye08Active: {{ DEYE08_ACTIVE }}

  - action: notify.mobile_app_jans_iphone
    data:
      title: Rescue charge
      message: >
        🟢 STARTET ({{ trigger.id|upper }}) Volt: {{
        states('sensor.solarcust0186_battery_voltage') }} V SOC: {{
        states('sensor.solarcust0186_battery_charge_level') }} % Load: {{
        states('sensor.solarcust0186_load_totalpower') }} W

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ IS_FAST }}"
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.deye08_active

          - action: switch.turn_on
            target:
              entity_id: switch.solarcust0186_grid_charge

          - action: number.set_value
            target:
              entity_id: number.solarcust0186_time_point_6_batt_charge_limit
            data:
              value: "{{ TARGET_SOC }}"

          - action: number.set_value
            target:
              entity_id: number.solarcust0186_maximum_battery_charge_current
            data:
              value: "{{ CHARGE_A }}"

          - action: number.set_value
            target:
              entity_id: number.solarcust0186_maximum_battery_grid_charge_current
            data:
              value: "{{ CHARGE_A }}"

          - action: number.set_value
            target:
              entity_id: number.solarcust0186_maximum_battery_discharge_current
            data:
              value: "{{ DISCHARGE_A_SAFE }}"

          - delay: "00:00:10"

  - repeat:
      while:
        - condition: template
          value_template: |
            {{ (states('sensor.solarcust0186_battery_voltage') | float(999)) <
               (STOP_VOLT | float) }}
      sequence:
        - choose:
            - conditions:
                - condition: template
                  value_template: >
                    {{ states('number.solarcust0186_time_point_6_batt_charge_limit')
                       | float(0) != (TARGET_SOC | float) }}
              sequence:
                - action: number.set_value
                  target:
                    entity_id: number.solarcust0186_time_point_6_batt_charge_limit
                  data:
                    value: "{{ TARGET_SOC }}"

        - choose:
            - conditions:
                - condition: template
                  value_template: >
                    {{ states('number.solarcust0186_maximum_battery_charge_current')
                       | float(0) != (CHARGE_A | float) }}
              sequence:
                - action: number.set_value
                  target:
                    entity_id: number.solarcust0186_maximum_battery_charge_current
                  data:
                    value: "{{ CHARGE_A }}"

        - choose:
            - conditions:
                - condition: template
                  value_template: >
                    {{ states('number.solarcust0186_maximum_battery_grid_charge_current')
                       | float(0) != (CHARGE_A | float) }}
              sequence:
                - action: number.set_value
                  target:
                    entity_id: number.solarcust0186_maximum_battery_grid_charge_current
                  data:
                    value: "{{ CHARGE_A }}"

        - choose:
            - conditions:
                - condition: template
                  value_template: >
                    {{ states('number.solarcust0186_maximum_battery_discharge_current')
                       | float(0) != (DISCHARGE_A_SAFE | float) }}
              sequence:
                - action: number.set_value
                  target:
                    entity_id: number.solarcust0186_maximum_battery_discharge_current
                  data:
                    value: "{{ DISCHARGE_A_SAFE }}"

        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ states('switch.solarcust0186_grid_charge') != 'on' }}"
              sequence:
                - action: switch.turn_on
                  target:
                    entity_id: switch.solarcust0186_grid_charge

        - action: persistent_notification.create
          data:
            notification_id: "{{ NOTIFY_ID }}"
            title: Rescue charge (kører)
            message: >
              🔄 Kører... ({{ trigger.id|upper }}) Volt: {{
              states('sensor.solarcust0186_battery_voltage') }} V SOC: {{
              states('sensor.solarcust0186_battery_charge_level') }} % Load: {{
              states('sensor.solarcust0186_load_totalpower') }} W BattP: {{
              states('sensor.solarcust0186_battery_output_power') }} W
              GridCharge: {{ states('switch.solarcust0186_grid_charge') }}
              ChargeA: {{ CHARGE_A }} A DischargeA: {{
              states('number.solarcust0186_maximum_battery_discharge_current') }}
              Delay: {{ LOOP_DELAY }} Deye08Active: {{ is_state('input_boolean.deye08_active','on') }}

        - delay: "{{ LOOP_DELAY }}"

  # STOP: sluk kun grid_charge hvis Deye-08 IKKE er aktiv
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ states('switch.solarcust0186_grid_charge') == 'on'
                 and not is_state('input_boolean.deye08_active','on') }}
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.solarcust0186_grid_charge

  # Mark Deye-08 as inactive (since Deye-01 is done)
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.deye08_active

  # RESTORE discharge kun hvis Deye-08 IKKE er aktiv
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ not is_state('input_boolean.deye08_active','on')
                 and (states('number.solarcust0186_maximum_battery_discharge_current') | float(0)
                      != (DISCHARGE_A_NORMAL | float)) }}
        sequence:
          - action: number.set_value
            target:
              entity_id: number.solarcust0186_maximum_battery_discharge_current
            data:
              value: "{{ DISCHARGE_A_NORMAL }}"

  - action: persistent_notification.create
    data:
      notification_id: "{{ NOTIFY_ID }}"
      title: Rescue charge
      message: >
        🛑 STOPPET Volt: {{ states('sensor.solarcust0186_battery_voltage') }} V
        SOC: {{ states('sensor.solarcust0186_battery_charge_level') }} %
        Discharge tilbage til: {{ DISCHARGE_A_NORMAL }} A Cooldown: {{ COOLDOWN }}
        (Deye08Active={{ is_state('input_boolean.deye08_active','on') }})

  - action: notify.mobile_app_jans_iphone
    data:
      title: Rescue charge
      message: >
        🛑 STOPPET Volt: {{ states('sensor.solarcust0186_battery_voltage') }} V
        SOC: {{ states('sensor.solarcust0186_battery_charge_level') }} %
        Cooldown: {{ COOLDOWN }}

  - delay: "{{ COOLDOWN }}"

mode: single

variables:
  STOP_VOLT: 50.2
  TARGET_SOC: 40
  CHARGE_A_PRE: 5
  CHARGE_A_FAST: 10
  DISCHARGE_A_NORMAL: 90
  DISCHARGE_A_SAFE: 10
  NOTIFY_ID: rescue_charge
  COOLDOWN: "00:30:00"