alias: "Deye-08: Low-Volt Guard (robust grid_charge + temporary SOC limits)"
description: "[v1.0.0] Low voltage guard that activates grid charging with temporary SOC limits during emergency voltage conditions. Robust handling of concurrent triggers."
tags:
  - deye-battery
  - rescue
  - critical
  - emergency
mode: queued
max: 10

triggers:
  - id: startup
    trigger: homeassistant
    event: start

  - id: emergency
    trigger: numeric_state
    entity_id: sensor.solarcust0186_battery_voltage
    below: 47.2

  - id: idle_low
    trigger: template
    value_template: |
      {{ (states('sensor.solarcust0186_battery_voltage') | float(999)) < 47.2
         and (states('sensor.solarcust0186_battery_output_power') | float(0)) | abs < 100
         and (states('switch.solarcust0186_grid_charge') != 'on') }}
    for: "00:01:00"

  # NEW: if grid_charge is changed while Deye-08 is active, enforce it back on
  - id: grid_charge_changed
    trigger: state
    entity_id: switch.solarcust0186_grid_charge

conditions:
  - condition: state
    entity_id: binary_sensor.solarcust0186_connection_status
    state: "on"
  - condition: state
    entity_id: switch.solarcust0186_inverter_automations_on_off
    state: "on"

actions:
  - variables:
      NOTIFY_ID: deye_low_volt_guard

      SOC_LIMIT_NORMAL: 20
      SOC_LIMIT_GUARD: 40

      CHARGE_A_IDLE: 4
      CHARGE_A_EMERGENCY: 5

      STOP_VOLT_IDLE: 48.2
      STOP_VOLT_EMERGENCY: 47.8

      LOOP_DELAY_IDLE: "00:01:00"
      LOOP_DELAY_EMERGENCY: "00:00:20"

      is_emergency: "{{ trigger.id == 'emergency' }}"
      is_voltage_guard_trigger: "{{ trigger.id in ['emergency','idle_low'] }}"
      is_grid_change: "{{ trigger.id == 'grid_charge_changed' }}"

      charge_a: "{{ CHARGE_A_EMERGENCY if is_emergency else CHARGE_A_IDLE }}"
      stop_volt: "{{ STOP_VOLT_EMERGENCY if is_emergency else STOP_VOLT_IDLE }}"
      loop_delay: "{{ LOOP_DELAY_EMERGENCY if is_emergency else LOOP_DELAY_IDLE }}"

      ev_active: "{{ is_state('input_boolean.deye_ev_charging_active','on') }}"
      deye08_active: "{{ is_state('input_boolean.deye08_active','on') }}"
      grid_charge_now: "{{ is_state('switch.solarcust0186_grid_charge','on') }}"
      volt: "{{ states('sensor.solarcust0186_battery_voltage') | float(999) }}"

  # STARTUP: set SOC limits back to normal (unless EV is active)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'startup' and not ev_active }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ states('number.solarcust0186_soba_low_batt_soc_limit') | float(0) != 20 }}"
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: number.solarcust0186_soba_low_batt_soc_limit
                    data:
                      value: 20
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ states('number.solarcust0186_batt_charge_limit') | float(0) != 20 }}"
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: number.solarcust0186_batt_charge_limit
                    data:
                      value: 20

  # If this is just grid_charge change and we are NOT active -> do nothing
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_grid_change and not deye08_active }}"
        sequence: []
    default:

      # If grid_charge was turned off while Deye-08 is active -> force it back ON
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ is_grid_change and deye08_active and not grid_charge_now }}"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.solarcust0186_grid_charge

      # If not a guard-trigger (emergency/idle_low), stop here after possible enforcement
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ not is_voltage_guard_trigger }}"
            sequence: []
        default:

          # Mark Deye-08 as active
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.deye08_active

          # Set SOC limits to 40 temporarily
          - service: number.set_value
            target:
              entity_id: number.solarcust0186_soba_low_batt_soc_limit
            data:
              value: 40
          - service: number.set_value
            target:
              entity_id: number.solarcust0186_batt_charge_limit
            data:
              value: 40

          # Set charge currents
          - service: number.set_value
            target:
              entity_id: number.solarcust0186_maximum_battery_charge_current
            data:
              value: "{{ charge_a }}"
          - service: number.set_value
            target:
              entity_id: number.solarcust0186_maximum_battery_grid_charge_current
            data:
              value: "{{ charge_a }}"

          # Turn grid charge ON
          - service: switch.turn_on
            target:
              entity_id: switch.solarcust0186_grid_charge

          # Loop until recovered
          - repeat:
              while:
                - condition: template
                  value_template: "{{ (states('sensor.solarcust0186_battery_voltage') | float(999)) < (stop_volt | float) }}"
              sequence:
                - delay: "{{ loop_delay }}"

                # enforce grid_charge still ON during recovery
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ states('switch.solarcust0186_grid_charge') != 'on' }}"
                      sequence:
                        - service: switch.turn_on
                          target:
                            entity_id: switch.solarcust0186_grid_charge

          # Stop: turn off grid charge
          - service: switch.turn_off
            target:
              entity_id: switch.solarcust0186_grid_charge

          # Mark inactive
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.deye08_active

          # Restore SOC limits to 20 (unless EV active)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not ev_active }}"
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: number.solarcust0186_soba_low_batt_soc_limit
                    data:
                      value: 20
                  - service: number.set_value
                    target:
                      entity_id: number.solarcust0186_batt_charge_limit
                    data:
                      value: 20