alias: Ecodan-02 - MELCloud Homey -> store values
description: Gemmer Homey MELCloud værdier + timestamp for hver webhook
triggers:
  - webhook_id: melcloud_homey
    trigger: webhook
actions:
  - target:
      entity_id: input_text.ecodan_last_payload_ts
    data:
      value: "{{ trigger.json['ts'] | default(now().isoformat()) }}"
    action: input_text.set_value
  - target:
      entity_id: input_text.ecodan_status
    data:
      value: "{{ trigger.json['status'] | default('unknown') }}"
    action: input_text.set_value
  - target:
      entity_id: input_text.ecodan_opstate
    data:
      value: "{{ trigger.json['opState'] | default('unknown') }}"
    action: input_text.set_value
  - target:
      entity_id: input_number.ecodan_outdoor
    data:
      value: "{{ trigger.json.outdoor | float(0) }}"
    action: input_number.set_value
  - target:
      entity_id: input_number.ecodan_flow_actual
    data:
      value: "{{ trigger.json.measurements.flowNow | float(0) }}"
    action: input_number.set_value
  - target:
      entity_id: input_number.ecodan_power
    data:
      value: "{{ trigger.json.measurements.powerNow | float(0) }}"
    action: input_number.set_value
  - target:
      entity_id: input_number.ecodan_frequency
    data:
      value: "{{ trigger.json.measurements.freqNow | float(0) }}"
    action: input_number.set_value
mode: queued
