alias: Ecodan-01 -> log good curve samples
description: ""
triggers:
  - webhook_id: melcloud_homey
    trigger: webhook
conditions:
  - condition: template
    value_template: "{{ (trigger.json['opState'] | default('')) == 'heating' }}"
  - condition: template
    value_template: >
      {% set st = trigger.json['status'] | default('') %} {{ not
      st.startswith('skipped_') }}
  - condition: template
    value_template: >
      {{ states('sensor.ecodan_outdoor_avg_60m') not in
      ['unknown','unavailable','none',''] and
         states('sensor.ecodan_flow_avg_10m') not in ['unknown','unavailable','none',''] }}
actions:
  - data:
      line: >
        {{ now().isoformat() }}, outdoor_avg_60m={{
        states('sensor.ecodan_outdoor_avg_60m') }}, flow_avg_10m={{
        states('sensor.ecodan_flow_avg_10m') }}, flowNow={{
        trigger.json.measurements.flowNow | default('') }}, powerNow={{
        trigger.json.measurements.powerNow | default('') }}, freqNow={{
        trigger.json.measurements.freqNow | default('') }}, opState={{
        trigger.json.opState | default('') }}, status={{ trigger.json.status |
        default('') }}
    action: shell_command.ecodan_curve_log_line
mode: queued
