alias: "Deye-Monitor-01 v1.0.2: Enhanced CSV Logging"
description: "Logs battery, inverter, automation data, and EV charging events to CSV file every minute. Tracks rescue states, EV webhooks, discharge enforcement, SOC limits, and voltage conditions."

triggers:
  - minutes: /1
    trigger: time_pattern
actions:
  - data:
      line: "{{ line }}"
    action: shell_command.deye_log_line
mode: queued
max: 5
variables:
  # Battery state
  batt_w: "{{ states('sensor.solarcust0186_battery_output_power') | float(0) }}"
  batt_mode: |-
    {% if batt_w > 50 %}
      discharge
    {% elif batt_w < -50 %}
      charge
    {% else %}
      idle
    {% endif %}
  batt_discharge_w: "{{ batt_w if batt_w > 0 else 0 }}"
  batt_charge_w: "{{ (batt_w * -1) if batt_w < 0 else 0 }}"
  
  # Automation state flags
  rescue_active: "{{ states('input_boolean.deye_rescue_active') }}"
  ev_charging_active: "{{ states('input_boolean.deye_ev_charging_active') }}"
  ev_charge_end_time: "{{ states('input_datetime.deye_ev_charge_end_time') }}"
  ev_webhook_count: "{{ states('counter.deye_ev_webhook_count') | int(0) }}"
  
  # Current values
  soc: "{{ states('sensor.solarcust0186_battery_charge_level') | float(50) }}"
  volt: "{{ states('sensor.solarcust0186_battery_voltage') | float(0) }}"
  max_discharge: "{{ states('number.solarcust0186_maximum_battery_discharge_current') | float(0) }}"
  max_charge: "{{ states('number.solarcust0186_maximum_battery_charge_current') | float(0) }}"
  max_grid_charge: "{{ states('number.solarcust0186_maximum_battery_grid_charge_current') | float(0) }}"
  
  # SOC-based limit calculation (Deye-02 v1.0.8 exponential curve)
  soc_min: 15
  soc_max: 45
  power_min_soc: 800
  power_max_soc: 2500
  boost: 1.05
  soc_power_limit_w: >-
    {% if soc >= soc_max %}
      {{ (power_max_soc * boost) | round(0) }}
    {% elif soc <= soc_min %}
      {{ (power_min_soc * boost) | round(0) }}
    {% else %}
      {% set normalized = (soc - soc_min) / (soc_max - soc_min) %}
      {% set exponential = normalized * normalized %}
      {{ ((power_min_soc + (power_max_soc - power_min_soc) * exponential) * boost) | round(0) }}
    {% endif %}
  soc_limit_a: "{{ ((soc_power_limit_w | float) / volt if volt > 1 else 48) | round(0) }}"
  
  # Seasonal logic
  month: "{{ now().month }}"
  is_winter: "{{ month in [10,11,12,1,2,3] }}"
  seasonal_discharge_a: "{{ 60 if is_winter else 90 }}"
  
  # Voltage conditions
  volt_status: |-
    {% if volt < 47.2 %}
      CRITICAL_EMERGENCY
    {% elif volt < 47.8 %}
      CRITICAL_LOW
    {% elif volt < 48.5 %}
      WARNING
    {% elif volt < 50.0 %}
      CAUTION
    {% else %}
      NORMAL
    {% endif %}
  
  # Low SOC charge guard (Deye-05 logic)
  is_critical_soc: "{{ soc < 20 }}"
  max_charge_guarded: "{{ 5 if is_critical_soc else 60 }}"
  
  # Zone name
  zone: "{{ states('input_text.deye_discharge_zone') }}"
  
  # CSV line - enhanced with EV webhook tracking
  line: >-
    {{ now().isoformat() }}, 
    soc={{ soc | round(1) }}, 
    volt={{ volt | round(2) }}, 
    volt_status={{ volt_status }},
    batt_w={{ batt_w }}, 
    batt_mode={{ batt_mode }}, 
    batt_discharge_w={{ batt_discharge_w }}, 
    batt_charge_w={{ batt_charge_w }}, 
    load_w={{ states('sensor.solarcust0186_load_totalpower') }},
    zone={{ zone }}, 
    grid_charge={{ states('switch.solarcust0186_grid_charge') }},
    rescue_active={{ rescue_active }},
    ev_charging_active={{ ev_charging_active }},
    ev_charge_end={{ ev_charge_end_time }},
    ev_webhook_count={{ ev_webhook_count }},
    max_discharge_a={{ max_discharge | round(0) }},
    max_charge_a={{ max_charge | round(0) }},
    max_grid_charge_a={{ max_grid_charge | round(0) }},
    soc_limit_a={{ soc_limit_a }},
    soc_power_w={{ soc_power_limit_w | round(0) }},
    is_critical_soc={{ is_critical_soc }}
